group: deprecated-2017Q4
language: java
jdk:
  - oraclejdk8
services:
  - docker
install:
  - sudo docker build -t bgppeer . 
  - docker_host=$(ifconfig docker0 | grep 'inet' | cut -d ':' -f2 | awk '{ print $1}')
  - echo $docker_host
script:
  - mvn install -X -f ./pom.xml
  - mvn -P generate-javadoc org.apache.maven.plugins:maven-javadoc-plugin:2.9.1:jar
  - sudo docker run -d -p 8087:8087 --add-host docker_host:$docker_host -t --name bgppeer1 bgppeer java -jar /usr/src/app/target/topology-SNAPSHOT-shaded.jar src/app/target/conf1wayTest/TM1.xml
  - sudo docker run -d -p 8088:8088 --add-host docker_host:$docker_host -t --name bgppeer2 bgppeer java -jar target/topology-SNAPSHOT-shaded.jar src/app/target//conf1wayTest/TM2.xml
  - sudo docker run -d -p 8089:8089 --add-host docker_host:$docker_host -t --name bgppeer3 bgppeer java -jar target/topology-SNAPSHOT-shaded.jar src/app/target/conf1wayTest/TM1.xml
  - nc -z -v -w5 $docker_host 8087
  - nc -z -v -w5 $docker_host 8088
  - nc -z -v -w5 $docker_host 8089
